name: rzk
version: 0.6.6
github: 'rzk-lang/rzk'
license: BSD3
author: 'Nikolai Kudasov'
maintainer: 'nickolay.kudasov@gmail.com'
copyright: '2023 Nikolai Kudasov'

extra-source-files:
  - README.md
  - ChangeLog.md
  - grammar/Syntax.cf

synopsis: An experimental proof assistant for synthetic ∞-categories
category: Dependent Types # same as Agda

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/rzk-lang/rzk#readme>

flags:
  lsp:
    description: >-
      Build with LSP support (only available with GHC, not GHCJS).
    manual: true
    default: true

custom-setup:
  dependencies:
    base:    ">= 4.11.0.0 && < 5.0"
    Cabal:   ">= 2.4.0.1 && < 4.0"
    process: ">= 1.6.3.0"

build-tools:
  alex:   ">= 3.2.4"
  happy:  ">= 1.19.9"
  BNFC:bnfc:   ">= 2.9.4.1"

dependencies:
  array: ">= 0.5.3.0"
  base: ">= 4.7 && < 5"
  bifunctors: ">= 5.5.3"
  bytestring: ">= 0.10.8.2"
  directory: ">= 1.2.7.0"
  Glob: ">= 0.9.3"
  mtl: ">= 2.2.2"
  optparse-generic: ">= 1.3.0"
  template-haskell: ">= 2.14.0.0"
  text: ">= 1.2.3.1"
  yaml: ">= 0.11.0.0"

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  # - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints
  - -optP-Wno-nonportable-include-path

library:
  source-dirs: src
  when:
    - condition: false
      other-modules:
        - Language.Rzk.Syntax.Test
        - Language.Rzk.Syntax.ErrM
        - Language.Rzk.Syntax.Skel
    - condition: flag(lsp) && !impl(ghcjs)
      exposed-modules:
        - Language.Rzk.VSCode.Env
        - Language.Rzk.VSCode.Handlers
        - Language.Rzk.VSCode.Lsp
        - Language.Rzk.VSCode.Tokenize
        - Language.Rzk.VSCode.Logging
      dependencies:
        aeson: ">= 1.4.2.0"
        co-log-core: ">= 0.3.2.0"
        data-default-class: ">= 0.1.2.0"
        filepath: ">= 1.4.2.1"
        lens: ">= 4.17"
        lsp: ">= 2.2.0.0"
        lsp-types: ">= 2.0.2.0"
        stm: ">= 2.5.0.0"
      cpp-options: -DLSP

executables:
  rzk:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - rzk
    when:
      - condition: "!impl(ghcjs)"
        dependencies:
          with-utf8: ">= 1.0.2.4"

tests:
  rzk-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - rzk

  doctests:
    source-dirs: test
    main: doctests.hs
    other-modules: []
    dependencies:
      - base
      - doctest
      - Glob
      - QuickCheck
      - template-haskell
