name: rzk
version: 0.6.3
github: 'rzk-lang/rzk'
license: BSD3
author: 'Nikolai Kudasov'
maintainer: 'nickolay.kudasov@gmail.com'
copyright: '2023 Nikolai Kudasov'

extra-source-files:
  - README.md
  - ChangeLog.md

synopsis: An experimental proof assistant for synthetic ∞-categories
category: Dependent Types # same as Agda

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/rzk-lang/rzk#readme>

flags:
  lsp:
    description: >-
      Build with LSP support.
    manual: true
    default: true

build-tools:
  alex:   ">= 3.2.4"
  happy:  ">= 1.19.9"

dependencies:
  array: ">= 0.5.3.0"
  aeson: ">= 1.4.2.0"
  base: ">= 4.7 && < 5"
  bifunctors: ">= 5.5.3"
  bytestring: ">= 0.10.8.2"
  mtl: ">= 2.2.2"
  template-haskell: ">= 2.14.0.0"
  text: ">= 1.2.3.1"
  optparse-generic: ">= 1.3.0"
  Glob: ">= 0.9.3"
  lens: ">= 4.17"
  filepath: ">= 1.4.2.1"
  stm: ">= 2.5.0.0"
  yaml: ">= 0.11.0.0"
  data-default-class: ">= 0.1.2.0"

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  # - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src
  when:
    - condition: false
      other-modules:
        - Language.Rzk.Syntax.Test
        - Language.Rzk.Syntax.ErrM
        - Language.Rzk.Syntax.Skel
    - condition: flag(lsp) && !impl(ghcjs)
      exposed-modules:
        - Language.Rzk.VSCode.Env
        - Language.Rzk.VSCode.Handlers
        - Language.Rzk.VSCode.Lsp
        - Language.Rzk.VSCode.State
        - Language.Rzk.VSCode.Tokenize
      dependencies:
        lsp: ">= 2.1.0.0"
        lsp-types: ">= 2.0.1.0"

executables:
  rzk:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - rzk
    when:
      - condition: flag(lsp) && !impl(ghcjs)
        dependencies:
          with-utf8: ">= 1.0.2.4"

tests:
  rzk-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - rzk

  doctests:
    source-dirs: test
    main: doctests.hs
    other-modules: []
    dependencies:
      - base
      - doctest
      - Glob
      - QuickCheck
      - template-haskell
