name:                rzk
version:             0.4.1
github:              "fizruk/rzk"
license:             BSD3
author:              "Nikolai Kudasov"
maintainer:          "nickolay.kudasov@gmail.com"
copyright:           "2023 Nikolai Kudasov"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            An experimental proof assistant for synthetic ∞-categories
category:            Dependent Types  # same as Agda

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/fizruk/rzk#readme>

dependencies:
- array
- base >= 4.7 && < 5
- bifunctors
- mtl
- template-haskell
- optparse-generic

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
# - -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  when:
  - condition: false
    other-modules:
    - Language.Rzk.Syntax.Test
    - Language.Rzk.Syntax.ErrM
    - Language.Rzk.Syntax.Skel

executables:
  rzk:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rzk

tests:
  rzk-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rzk
