authors:
  fizruk:
    name: Nikolai Kudasov
    description: Random guy
    avatar: https://avatars.githubusercontent.com/u/686582
    url: https://github.com/fizruk
  aabounegm:
    name: Abdelrahman Abounegm
    description: Language Server maintainer
    avatar: https://avatars.githubusercontent.com/u/11016151
    url: https://github.com/aabounegm
