repo_url: https://github.com/rzk-lang/rzk
repo_name: rzk-lang/rzk

theme:
  name: material
  custom_dir: '../../overrides/'
  favicon: assets/images/favicon.png
  logo: assets/images/logo-1000x1000.png
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
  features:
    - content.code.copy
    - content.action.edit
    - navigation.footer
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path

extra_javascript:
  - javascript/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/styles/default.min.css
  - assets/css/rzk-render.css

markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.snippets:
      base_path:
        - .
        - ..
      check_paths: true
  - mdx_math
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  version:
    provider: mike
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: Русский
      link: /ru/
      lang: ru

plugins:
  - rzk:
      render_svg: true
      anchor_definitions: true
