[book]
authors = ["Nikolai Kudasov"]
language = "en"
multilingual = false
src = "."
title = "RZK (prototype proof assistant)"

[build]
build-dir = "out"

[output.html]
git-repository-url = "https://github.com/fizruk/rzk"

[output.html.playground.boring-prefixes]
rzk = "# "
