site_name: "rzk: an experimental proof assistant for synthetic ∞-categories"
repo_url: https://github.com/rzk-lang/rzk
repo_name: rzk-lang/rzk
edit_uri: edit/develop/docs/docs/

nav:
  - General:
    - About: index.md
    - Contributors: CONTRIBUTORS.md
    - Changelog: CHANGELOG.md
  - Getting Started:
    - Install: getting-started/install.md
    - Quickstart: getting-started/quickstart.rzk.md
    - Publishing with MkDocs: getting-started/publishing-with-mkdocs.md
  - Reference:
    - Introduction: reference/introduction.rzk.md
    - Cube layer: reference/cube-layer.rzk.md
    - Tope layer: reference/tope-layer.rzk.md
    - Dependent types: reference/type-layer.rzk.md
    - Tope disjunction elimination: reference/tope-disjunction-elimination.rzk.md
    - Extension types: reference/extension-types.rzk.md
    - Organizational features:
      - Sections and Variables: reference/sections.rzk.md
    - Builtins:
      - Directed interval: reference/builtins/directed-interval.rzk.md
      - Unit type: reference/builtins/unit.rzk.md
    - Commands:
      - Define and Postulate: reference/commands/define-postulate.rzk.md
      - Compute: reference/commands/compute.rzk.md
      - Check: reference/commands/check.rzk.md
      - Options: reference/commands/options.rzk.md
    - Other:
      - Rendering Diagrams: reference/render.rzk.md
  - Examples:
    - Weak tope disjunction elimination: examples/recId.rzk.md
  - Tools:
    - Syntax Highlighting: tools/highlight.md
    - IDE support: tools/ide.md
    - Continuous Verification: tools/continuous.md
  - Related Projects:
    - Yoneda lemma for ∞-categories: related/yoneda.md
    - sHoTT: related/sHoTT.md
    - simple-topes: related/simple-topes.md
  - Playground: playground/

markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.details
  - mdx_math
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg


theme:
  name: material
  custom_dir: overrides
  favicon: assets/images/favicon.png
  logo: assets/images/logo-1000x1000.png
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
  features:
    - content.code.copy
    - content.action.edit
    - navigation.footer
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: white
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_javascript:
  - javascript/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/styles/default.min.css
  - assets/css/rzk-render.css

extra:
  version:
    provider: mike

plugins:
  - mike
  - rzk:
      render_svg: true
      anchor_definitions: true
  - search
