site_name: "rzk: an experimental proof assistant for syntheric ∞-categories"
nav:
  - General:
    - About: index.md
  - rzk-1 Language:
    - Introduction: rzk-1/introduction.md
    - Weak tope disjunction elimination: rzk-1/recId.md
  - Tools:
    - IDE support: tools/ide.md
    - Continuous Verification: tools/continuous.md
  - Related Projects:
    - sHoTT: related/sHoTT.md
    - simple-topes: related/simple-topes.md

markdown_extensions:
  - admonition
  - mdx_math

theme:
  name: readthedocs
  highlightjs: false  # we override default hightlightjs in custom_theme/
  custom_dir: custom_theme/
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/styles/default.min.css
