INHERIT: "../base.yml"
site_url: https://rzk-lang.github.io/rzk/en/
site_name: "Rzk proof assistant"
site_description: "An experimental proof assistant for simplicial type theory and synthetic ∞-categories."
site_author: "Nikolai Kudasov"
docs_dir: '../../docs/en'
site_dir: '../../generated/en'
edit_uri: edit/blog/docs/docs/en/

nav:
  - About: https://rzk-lang.github.io/rzk/en/latest/
  - Getting Started: https://rzk-lang.github.io/rzk/en/latest/getting-started/
  - Reference: https://rzk-lang.github.io/rzk/en/latest/reference/
  - Playground: https://rzk-lang.github.io/rzk/en/latest/playground/
  - Blog:
    - index.md

theme:
  language: en
  font:
    text: Inria Sans
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: white
      scheme: default
      toggle:
        icon: material/brightness-7
        name: "Switch to dark mode"
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: "Switch to light mode"

plugins:
  - blog:
      blog_dir: .
  - rss:
      match_path: posts/.*
      date_from_meta:
        as_creation: date
      categories:
        - categories
        # - tags
  - social
  - mike:
      deploy_prefix: 'en/'
  - search:
      lang: en
  - rzk:
      render_svg: true
      anchor_definitions: true
