# This is a basic workflow to help you get started with Actions

name: Build with GHCJS and Deploy to GitHub Pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths:
      - rzk/**
      - try-rzk/**
      - stack.yaml
  pull_request:
    branches: [ main ]
    paths:
      - rzk/**
      - try-rzk/**
      - stack.yaml

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  ghcjs:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 🧰 Setup nix (cache)
        uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          # pinning Nix version
          install_url: https://releases.nixos.org/nix/nix-2.13.3/install

      - name: 💾 Setup cachix (miso-haskell)
        uses: cachix/cachix-action@v10
        with:
          name: miso-haskell

      - name: 🔨 Build GHCJS version with Nix
        run: |
          nix-build try-rzk/
          mkdir -p dist/result/bin
          cp -r ./result/bin/try-rzk.jsexe/ dist/result/bin/.
          chmod -R +w dist/
          cp try-rzk/index.html dist/.

      - name: "📘 Publish JS \"binaries\""
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          folder: dist
          clean: false
