name: Build with GHCJS and Deploy to GitHub Pages

on:
  push:
    branches: [ main, develop ]
    tags: [ v* ]
    paths:
      - rzk/**
      - try-rzk/**
      - stack.yaml
  pull_request:
    branches: [ main, develop ]
    paths:
      - rzk/**
      - try-rzk/**
      - stack.yaml

  workflow_dispatch:  # allow triggering this workflow manually

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 🧰 Setup nix (cache)
        uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          # pinning Nix version
          install_url: https://releases.nixos.org/nix/nix-2.13.3/install

      - name: 💾 Setup cachix (miso-haskell)
        uses: cachix/cachix-action@v10
        with:
          name: miso-haskell

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: 🔨 Build GHCJS version with Nix
        run: |
          nix-build try-rzk/
          mkdir -p dist/result/bin
          cp -r ./result/bin/try-rzk.jsexe/ dist/result/bin/.
          chmod -R +w dist/
          cp try-rzk/index.html dist/.

  deploy:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: "📘 Publish JS \"binaries\""
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          folder: dist
          target-folder: ${{ GITHUB_REF_NAME }}
          clean: false
