name: Documentation

on:
  push:
    branches:
      - "main"

jobs:
  docs:
    runs-on: ubuntu-latest
    env:
      STACK_ROOT: ${{ github.workspace }}/.stack

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v2

      - name: 🧰 Setup Stack
        uses: haskell/actions/setup@v1
        with:
          enable-stack: true

      - name: 🧰 Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: '0.4.6'
          # mdbook-version: 'latest'

      - name: 💾 Cache
        uses: actions/cache@v2
        with:
          path: |
            .stack
          key: ${{ runner.os }}-${{ hashFiles('stack.yaml.lock', 'rzk.cabal') }}-stack

      - name: 🔨 Build Haddock Documentation
        run: |
          stack haddock
          mkdir -p dist/haddock
          mv $(stack path --local-doc-root)/* dist/haddock

      - name: 🔨 Build mdBook
        run: |
          mdbook build docs/
          mkdir -p dist/
          mv docs/out/* dist/

      - name: 📘 Publish Documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          force_orphan: true
