# This is a basic workflow to help you get started with Actions

name: Build and Deploy Haddock to GitHub Pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths:
      - rzk/**
      - stack.yaml

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  haddock:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 🧰 Setup Stack
        uses: haskell/actions/setup@v1
        with:
          enable-stack: true

      - name: 💾 Cache .stack/
        uses: actions/cache@v2
        with:
          path: |
            .stack
          key: ${{ runner.os }}-${{ hashFiles('stack.yaml.lock', 'rzk.cabal') }}-stack

      - name: 🔨 Install BNFC, alex and happy (with Stack)
        run: |
          stack install alex happy BNFC
      - name: 🔨 Generate Syntax files using BNFC
        run: |
          cd stella/ && (make syntax && make clean; cd ../)

      - name: 🔨 Build Haddock Documentation (with Stack)
        run: |
          stack haddock
          mkdir -p dist/haddock
          mv $(stack path --local-doc-root)/* dist/haddock

      - name: 📘 Publish Haddock Documentation
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          folder: dist/haddock
          target-folder: haddock
