# This is a basic workflow to help you get started with Actions

name: Build and Deploy MkDocs to GitHub Pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths:
      - docs/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  mkdocs:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: 📥 Checkout repository
        uses: actions/checkout@v2

      - name: 🧰 Setup Python
        uses: actions/setup-python@v1

      - name: 🔨 Build MkDocs
        uses: Tiryoh/actions-mkdocs@v0
        with:
          mkdocs_version: 'latest' # option
          #mkdocs_version: '1.1' # option
          requirements: 'docs/requirements.txt' # option
          configfile: 'docs/mkdocs.yml' # option

      - name: 🔨 Copy MkDocs files
        run: |
          mkdir -p dist/ && cp -r docs/split.html docs/site dist/.

      - name: 📘 Publish Generated MkDocs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          folder: dist
