name: Build and Deploy MkDocs to GitHub Pages

on:
  push:
    branches: [ main, develop ]
    tags: [ v* ]
    paths:
      - .github/workflows/mkdocs.yml
      - docs/**

  workflow_dispatch:

jobs:
  mkdocs:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 🔨 Install rzk proof assistant
        uses: jaxxstorm/action-install-gh-release@v1.10.0
        with:
          repo: fizruk/rzk
          tag: v0.4.1
          rename-to: rzk

      - name: 🔨 Build MkDocs
        uses: Tiryoh/actions-mkdocs@v0
        with:
          mkdocs_version: 'latest' # option
          #mkdocs_version: '1.1' # option
          requirements: 'docs/requirements.txt' # option
          configfile: 'docs/mkdocs.yml' # option

      - name: 🔨 Copy MkDocs files
        run: |
          mkdir -p dist/ && cp -r docs/root/* docs/site dist/.

      - name: 📘 Publish Generated MkDocs (${{ github.ref_name }})
        if: ${{ github.ref_name != 'main' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          folder: dist
          target-folder: ${{ github.ref_name }}
          clean: false
          single-commit: true

      - name: 📘 Publish Generated MkDocs
        if: ${{ github.ref_name == 'main' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          folder: dist
          clean: false
          single-commit: true
